# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'  # Optional: Set memory limit for Maven
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'  # Matches the Java version in our pom.xml
    jdkArchitectureOption: 'x64'
    goals: 'clean install'
  displayName: 'Build with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'  # Test result files from Maven Surefire plugin
    testRunTitle: 'Java Client Tests'
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/target'  # Artifacts from the build
    artifactName: 'java-client-automation-artifacts'
    publishLocation: 'pipeline'
  displayName: 'Publish Build Artifacts'
