# Maven
# Build Java project and run tests with Apache Maven.

trigger:
      - main

pool:
  vmImage: 'windows-latest'

steps:
# Step to install Node.js to support JSON server
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# Step to install JSON Server globally
- script: npm install -g json-server
  displayName: 'Install JSON Server'

# Step to start JSON Server in the background on Windows
- script: |
    start /b json-server --watch $(System.DefaultWorkingDirectory)/db.json --port 3000
  displayName: 'Start JSON Server'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    goals: 'clean install -Dmaven.test.failure.ignore=true'
    options: '-Dsurefire.suiteXmlFiles=testng.xml -Dtest=!com.application.tests.mobile.AndroidTest -DfailIfNoTests=false'
  displayName: 'Build with Maven (Exclude AndroidTest)'

# Publish JUnit Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/target/surefire-reports/TEST-*.xml'
    testRunTitle: 'Java Client Tests'
  displayName: 'Publish JUnit Test Results'
